# Generated by Django 3.2.12 on 2022-03-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_userfollows_userfollow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollow',
            options={},
        ),
    ]
